apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp-deployment
  labels:
    app:  MYAPP
    type: front-end
spec:
  selector:
    matchLabels:
      type: front-end
  replicas: 3
  template:
    metadata:
      labels:
        app: MYAPP
        type: front-end
    spec:
      containers:
      - name:  nginx-container
        image:  nginx